title: DevOps Pradeep Yadav
email: lovelypy1001@gmail.com
description: >-
  Cloud Native, DevSecOps, and Infrastructure Engineering Blogs.
baseurl: "" 
url: "" 

# -----------------------------
# 1. URL Structure (CRITICAL)
# -----------------------------
permalink: /blog/:title/

# -----------------------------
# 2. Build Settings
# -----------------------------
markdown: kramdown
#theme: minima
plugins:
  - jekyll-paginate

# -----------------------------
# 3. Pagination Logic
# -----------------------------
paginate: 6
paginate_path: "/blog/page:num/"